[package]
name = "size-tools"
version = "0.1.0"
authors = ["Philipp Vollmer <philipp.vollmer@tngtech.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
elf = "0.0.10"
clap = "2.33.0"
